version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agentfleet
      - AGENTFLEET_ENVIRONMENT=DEVELOPMENT
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json
    volumes:
      - ./backend:/app
      - ./service-account-key.json:/app/key.json:ro
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_ENVIRONMENT=DEVELOPMENT
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=agentfleet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
